# Generated by Django 3.1.2 on 2020-10-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='键')),
                ('value', models.CharField(max_length=5000, verbose_name='值')),
            ],
            options={
                'verbose_name': '系统字段',
                'verbose_name_plural': '系统字段',
            },
        ),
    ]
