# Generated by Django 3.1.1 on 2020-10-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名')),
                ('needreply', models.IntegerField(default=0, verbose_name='需要系统回复')),
            ],
            options={
                'verbose_name': '话题分类',
                'verbose_name_plural': '话题分类',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='回复人')),
                ('pid', models.IntegerField(default=1, verbose_name='回复话题')),
                ('check', models.IntegerField(default=0, verbose_name='审核')),
                ('content', models.TextField(verbose_name='回复内容')),
                ('imgs', models.TextField(verbose_name='图片')),
                ('like', models.IntegerField(default=0, verbose_name='点赞数')),
                ('create_time', models.CharField(max_length=20, verbose_name='回复时间')),
                ('user_delete', models.CharField(max_length=20, null=True, verbose_name='(自行)删除时间')),
                ('system_delete', models.CharField(max_length=20, null=True, verbose_name='(系统)删除时间')),
            ],
            options={
                'verbose_name': '话题评论',
                'verbose_name_plural': '话题评论',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aid', models.IntegerField(verbose_name='话题发起人')),
                ('rname', models.CharField(default='系统', max_length=50, verbose_name='回复人名字')),
                ('tid', models.IntegerField(verbose_name='回复的话题')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.CharField(max_length=20, verbose_name='系统回复时间')),
            ],
            options={
                'verbose_name': '后台回复',
                'verbose_name_plural': '后台回复',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='发表人')),
                ('pid', models.IntegerField(default=1, verbose_name='分类')),
                ('check', models.IntegerField(default=0, verbose_name='审核')),
                ('name', models.CharField(max_length=100, verbose_name='要显示的名字')),
                ('headimg', models.CharField(max_length=300, verbose_name='要显示的头像')),
                ('title', models.CharField(max_length=40, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('imgs', models.TextField(verbose_name='图片(以列表形式)')),
                ('hide', models.IntegerField(default=0, verbose_name='是否匿名')),
                ('top', models.IntegerField(default=0, verbose_name='是否置顶')),
                ('like', models.IntegerField(default=0, verbose_name='点赞数')),
                ('dislike', models.IntegerField(default=0, verbose_name='倒赞数')),
                ('visit', models.IntegerField(default=0, verbose_name='阅读数')),
                ('create_time', models.CharField(max_length=20, verbose_name='创建时间')),
                ('user_delete', models.CharField(max_length=20, null=True, verbose_name='(自行)删除时间')),
                ('system_delete', models.CharField(max_length=20, null=True, verbose_name='(系统)删除时间')),
            ],
            options={
                'verbose_name': '话题内容',
                'verbose_name_plural': '话题内容',
            },
        ),
    ]
